name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Running commands on runner machine
      runs: 
        echo "hello"
        ls -al
        pwd
        touch hello.txt
    
